### ISSUE TITLE
Debugging?

### ISSUE THREAD

**Issue by svanimpe** [vknabel/vscode-swift-development-environment#4]
In your Quick Preview, you show the debugger in action. How can I get this working? The link to the hands-on introduction (http://blog.dirac.io/2017/01/11/get_started_sde.html) is broken.

**Comment by vknabel** [comment]
@svanimpe thank you for your feedback!
Seems like the whole domain is down. I will add some documentation here on Github in order to avoid this case.

Regarding the debugger:
1. Open your SPM project in vscode
2. Open a Swift-file (this will start the extension; will be changed in future updates)
3. Now you can add a configuration `Swift Debug` (if not, simply copy the json into your `launch.json`)

The `launch.json` should now contain something similar to

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "swift-debug",
            "request": "launch",
            "name": "Swift Program Debug",
            "program": "${workspaceRoot}/.build/debug/path-to-program-debugged"
        }
    ]
}
```

4. Now change the `configurations.program` path to the name of your target to be tested.

**Comment by svanimpe** [comment]
Hmm. I did this but every time I try to launch, I get the following error: "Debug adapter process has terminated unexpectedly". In the extensions output window, I see:

```
(node:45788) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'getThreads' of null
(node:45788) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.(node:45792) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'getThreads' of null
(node:45792) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My `launch.json` file:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "swift-debug",
            "request": "launch",
            "name": "Debug Program",
            "program": "${workspaceRoot}/.build/debug/swift-test"
        }
    ]
}
```

**Comment by vknabel** [comment]
@svanimpe the file you are providing must exist. 
The debugger currently works best for executables. In case of the Sourcery project you would nee to provide `${workspaceRoot}/.build/debug/sourcery` [krzysztofzablocki/Sourcery/Package.swift#L7](https://github.com/krzysztofzablocki/Sourcery/blob/master/Package.swift#L7).

If you are interested in debugging your unit tests, it is not explicitly supported by now, but depending on your environment it may actually work https://github.com/jinmingjian/sde/issues/27.

**Comment by svanimpe** [comment]
The file does exist. I can execute it just fine on the command-line. I assume `${workspaceRoot}` is the project's root directory (where `Package.swift` is)?

**Comment by vknabel** [comment]
@svanimpe In case your manifest is located at `~/org/project/Package.swift` and you open `code ~/org/project` then `${workspaceRoot}` would be `~/org/project`, but if you would `code ~/org` then `${workspaceRoot}` would only be `~/org`.

Is the project you are working with open source? In that case I could try it on your project myself.

**Comment by svanimpe** [comment]
Yes I've opened the project's main folder in VS Code, not a parent or subfolder.

My project is simply hello world (`swift package init --type=executable`) to which I've added that launch file you suggested.

**Comment by svanimpe** [comment]
I have also tried using an explicit path (without using `${workspaceRoot}`) with no success.

**Comment by vknabel** [comment]
@svanimpe I did try it on my machine, but it worked.
I am running the latest Xcode and tried it with Swift 4.0 and 4.0.2. Are you using linux?

```bash
$ mkdir swift-test
$ cd swift-test
$ swift package init --type=executable
Creating executable package: swift-test
Creating Package.swift
Creating README.md
Creating .gitignore
Creating Sources/
Creating Sources/swift-test/main.swift
Creating Tests/
$ code .
$ pbpaste > .vscode/launch.json # with your file copied
# Now I set a breakpoint in `Sources/swift-test/main.swift` on the first line
# When I ran the debugger it stopped at line 1
```

**Comment by svanimpe** [comment]
That is exactly what I did, but it doesn't work for me. I get the error listed above.

I am using Xcode 9.1. I also have Swift 4.0.2 installed from swift.org. My VS Code is version 1.18.0

**Comment by vknabel** [comment]
I did not forget you, but I couldn't reproduce it yet.

**Comment by vknabel** [comment]
@svanimpe I just released 2.1.2 which might fix your issue. I still couldn‘t reproduce your issue, but by looking at the code I could find a case, that may lead to this behavior. 

If this doesn‘t fix the issue for you, let me know.

**Comment by svanimpe** [comment]
Nope, still `Debug adapter process has terminated unexpectedly`.  I no longer see the the `UnhandledPromiseRejectionWarning`, but debugging still doesn't work.

Do I need up update sourcekite as well? I've only reloaded the plugin to get version 2.1.2.

**Comment by vknabel** [comment]
@svanimpe There is no new update for `sourcekite`, but maybe it helps.

**Comment by vknabel** [comment]
@svanimpe As stated in [README.md#Debugging](https://github.com/vknabel/vscode-swift-development-environment#debugging) I deprecated the debugger as there is a better and more stable alternative called [LLDB Debugger](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb).
